# ===================================================================
# Profil de configuration pour l'exécution locale (localhost)
# ===================================================================

# Configuration des APIs
app.theses.api-base-url=https://v2-test.theses.fr/api/v1
app.theses.page-size=1000

# Configuration data.gouv.fr (avec clés de test issues du .env local)
app.datagouv.api-key=
app.datagouv.dataset-id=
app.datagouv.csv-resource-id=
app.datagouv.json-resource-id=
app.datagouv.ndjson-resource-id=
app.datagouv.upload-enabled=false

# Paramètres du Batch en local
app.mode-test=true
app.output-dir=./data

# Planification et exécution immédiate au démarrage
app.scheduler.enabled=false
app.force-run=false
